/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.binaryelysium.android.parley;

public final class R {
    public static final class anim {
        public static final int push_left_in=0x7f040000;
        public static final int push_left_out=0x7f040001;
        public static final int push_right_in=0x7f040002;
        public static final int push_right_out=0x7f040003;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher_folder=0x7f020000;
        public static final int ic_launcher_folder_small=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int icon_file=0x7f020003;
        public static final int list_group_header=0x7f020004;
        public static final int list_item_focus_fullwidth=0x7f020005;
        public static final int list_item_rest_arrow=0x7f020006;
        public static final int list_item_rest_fullwidth=0x7f020007;
    }
    public static final class id {
        public static final int FCViewFlipper=0x7f060004;
        public static final int ViewFlipper=0x7f06000e;
        public static final int file_details=0x7f060003;
        public static final int file_icon=0x7f060001;
        public static final int file_name=0x7f060002;
        public static final int lessons_list_view=0x7f06000f;
        public static final int list_header_title=0x7f060007;
        public static final int row_disclosure_icon=0x7f06000b;
        public static final int row_icon=0x7f060008;
        public static final int row_label=0x7f060009;
        public static final int row_label_second=0x7f06000a;
        public static final int start_practice=0x7f06000d;
        public static final int station_row=0x7f060000;
        public static final int status=0x7f06000c;
        public static final int word1=0x7f060005;
        public static final int word2=0x7f060006;
        public static final int words_table=0x7f060010;
    }
    public static final class layout {
        public static final int file_item=0x7f030000;
        public static final int file_listing=0x7f030001;
        public static final int flashcard=0x7f030002;
        public static final int list_header=0x7f030003;
        public static final int list_row=0x7f030004;
        public static final int main=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
}
